"""empty message

Revision ID: 27045c5738b8
Revises: db4ffbe58b27
Create Date: 2017-03-19 22:16:06.610317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27045c5738b8'
down_revision = 'db4ffbe58b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'image_thumb_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('image_thumb_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
